### ISSUE TITLE
Error searching torrents

### ISSUE THREAD

**Issue by adrienlabigne** [Ripolin/potatoygg#20]
Hey, two days ago, all was running good, but from yesterday, I got these errors...
Don't know if it's a problem from CP or Potatoygg (https://github.com/Ripolin/potatoygg)

Thanks. 

### Steps to reproduce:
1. Manual search for a movie on Yggtorrent

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: 720p/1080p
Providers I use: Yggtorrent
Version of CouchPotato: git:(CouchPotato:CouchPotatoServer master) 75e576ee (2019-01-13 14:13:34)
Running on: Synology DS415Play

### Logs:
```
07-01 10:46:05 INFO [hpotato.core.plugins.base] Opening url: get https://www.omdbapi.com/?apikey=xxx&type=movie&i=tt8398768, data: [] 
07-01 10:46:09 INFO [core.media.movie.searcher] Search for Mon Ket in 720p 
07-01 10:46:09 INFO [hpotato.core.plugins.base] Opening url: get https://www2.yggtorrent.ch/engine/search?category=2145&do=search&sub_category=all&name=mon+ket&file=&uploader=&description=, data: [] 
07-01 10:46:12 ERROR [hpotato.core.plugins.base] Failed opening url in OMDBAPI: https://www.omdbapi.com/?apikey=xxx&type=movie&i=tt8398768 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.omdbapi.com', port=443): Read timed out. (read timeout=3)
 
07-01 10:46:39 ERROR [hpotato.core.plugins.base] Failed opening url in CouchPotatoApi: https://api.couchpota.to/info/tt8398768/?ignore=1 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='api.couchpota.to', port=443): Read timed out. (read timeout=30)
 
07-01 10:46:39 INFO [hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/w154/hbwwGRlCidC6zGRaAIJAJ0vlDcZ.jpg, data: [] 
07-01 10:46:40 ERROR [hpotato.core.plugins.base] Failed opening url in YGG: https://www2.yggtorrent.ch/engine/search?category=2145&do=search&sub_category=all&name=mon+ket&file=&uploader=&description= Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www2.yggtorrent.ch', port=443): Read timed out. (read timeout=30)
 
07-01 10:46:40 INFO [core.media.movie.searcher] Search for Mon Ket in 1080p 
07-01 10:46:40 INFO [hpotato.core.plugins.base] Opening url: get https://www2.yggtorrent.ch/engine/search?category=2145&do=search&sub_category=all&name=mon+ket&file=&uploader=&description=, data: [] 
07-01 10:47:09 ERROR [hpotato.core.plugins.base] Failed opening url in FileManager: https://image.tmdb.org/t/p/w154/hbwwGRlCidC6zGRaAIJAJ0vlDcZ.jpg Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='image.tmdb.org', port=443): Read timed out. (read timeout=30)
 
07-01 10:47:10 ERROR [hpotato.core.plugins.file] Failed downloading file https://image.tmdb.org/t/p/w154/hbwwGRlCidC6zGRaAIJAJ0vlDcZ.jpg: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/file.py", line 79, in download
    filedata = self.urlopen(url, **urlopen_kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/adapters.py", line 431, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='image.tmdb.org', port=443): Read timed out. (read timeout=30)
 
07-01 10:47:10 INFO [hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/w154/hbwwGRlCidC6zGRaAIJAJ0vlDcZ.jpg, data: [] 
07-01 10:47:10 ERROR [to.core.media.movie._base] Failed update media: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/movie/_base/main.py", line 312, in update
    db.update(media)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/CodernityDB/database.py", line 917, in update
    _id, new_rev = self._update_indexes(_rev, data)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/CodernityDB/database.py", line 678, in _update_indexes
    _id, new_rev, db_data = self._update_id_index(_rev, data)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/CodernityDB/database.py", line 666, in _update_id_index
    raise RevConflict()
RevConflict
 
07-01 10:47:10 INFO [core.media.movie.searcher] Search for Mon Ket in 720p ignoring ETA 
07-01 10:47:17 INFO [core.media.movie.searcher] Search for Mon Ket in 1080p ignoring ETA 
```

**Comment by adrienlabigne** [comment]
Ah et bien il semble que Ygg ai des soucis aujourd'hui, erreur 503 sur le site.
Un autre film à bien voulu se dl après celui-ci...
Bref, wait&see
